### ISSUE TITLE
[help] How do I dynamically reference the Github library(seems your code did)?

### ISSUE THREAD

**Issue by zhongqingsong** [springmusk026/Il2cppDumper-Android#1]
Hello, When I scanned your source code, I found a feature I had been looking for!!! It's cool!!! But I dont know how. Can you tell me how you did that, thank you very much.
![image](https://user-images.githubusercontent.com/35858818/179953017-6ec8ed9c-9655-4301-baf0-42e88d179649.png)

Description:
As shown above, When I click on the Dobby folder, It automatically jumps to Dobby's open source project home page.So, I think this is a dynamically referenced third-party library: 
When we reference a third party library, the common practice is to download its library file, The project then loads the file. It's work. But when the 3rd library has some change. You can't synchronize those changes. You will have to download the library file again.
When those files were few, it was fine. However, if there are many content files in the library file, the new library file will have to be cleaned up before the new file is loaded. That's not good.

It seems that your code solves this problem. Your code is directly linked to the original project, even if the referenced project updates the code. You can also receive timely notifications and easily update to the latest library files.

Of course, this is all my guess. If MY guess is correct, please tell me how. Thank you very much!!!

**Comment by springmusk026** [comment]
look build.gradle its has a setup there along with prefab

**Comment by zhongqingsong** [comment]
ok, got it. 
Thank you 
: )
